name: 🚀 Deploy website on push

on: 
  push:
    branches: 
      - master

jobs:
   web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          server-dir: www/
          exclude: |
            **/.git*
            **/.git*/**
            LICENSE
            README.md
            index.txt
